name: cbc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.8
  local_auth: ^2.2.0
  sp_util: ^2.0.3
  event_bus: ^2.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  dio: ^5.3.2
  cached_network_image: ^3.2.1
  permission_handler: any
  path_provider: ^2.1.5  # 用于获取本地文件路径（可选）
  flutter_smart_dialog: ^4.9.8+7
  common_utils: 2.1.0
  pull_to_refresh_flutter3: ^2.0.1
  flutter_local_notifications: 19.0.0
  device_info_plus: ^9.0.0
  card_swiper: ^3.0.1
  syncfusion_flutter_charts: any
  scrollable_positioned_list: any
  easy_sticky_header: ^1.1.1
  lpinyin: 2.0.3
  azlistview: 2.0.0
  pretty_qr_code: ^3.5.0
  visibility_detector: 0.4.0+2
  qr_code_scanner_plus: ^2.0.10+1
  flutter_neat_and_clean_calendar: ^0.4.16
  scroll_screenshot: any
  flutter_inappwebview: 6.1.5
  open_file: ^3.3.2
  audioplayers: ^6.0.0
  wb_base_widget:
    path: modules/wb_base_widget
  flutter_picker_plus:
    path: modules/flutter_picker_plus
  f_verification_box:
    path: modules/f_verification_box
  gallery_saver_plus:
    path: modules/gallery_saver_plus
  popup_menu: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/


  fonts:
    - family: cbc
      fonts:
        - asset: assets/ttf/cbc.ttf
    - family: cbc-num
      fonts:
        - asset: assets/ttf/MiSans-Regular.ttf
          weight: 400
        - asset: assets/ttf/MiSans-Normal.ttf
          weight: 500
        - asset: assets/ttf/MiSans-Medium.ttf
          weight: 600
        - asset: assets/ttf/MiSans-Bold.ttf
          weight: 700
        - asset: assets/ttf/MiSans-Semibold.ttf
          weight: 800
    - family: cbc-num-dot
      fonts:
        - asset: assets/ttf/Inter-Medium.otf
        - asset: assets/ttf/Inter-Regular.otf